services:
  postgres:
    image: postgres:latest
    container_name: marcador-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    restart: always

  mailpit:
    image: axllent/mailpit:edge
    container_name: marcador-mailpit
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATABASE: ""
    ports:
      - "${MAILSENDER_PORT}:1025"
      - "${MAIL_INTERFACE_PORT}:8025"
    restart: unless-stopped

  api:
    image: marcador-api:0.0.1
    container_name: marcador-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      - postgres
